config/routes.rb
Santa4Cyclists::Application.routes.draw do
  resources :items

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :products

  get "/registration",   to: 'users#new'
  get '/login',          to: 'sessions#new'
  get '/logout',         to: 'sessions#destroy'
  get '/search',         to: 'static_pages#search'
  get '/nav_bar_reload', to: 'static_pages#nav_bar_reload'

  root :to => 'static_pages#home'

end

app/views/layouts/_header.html.erb
<header class="master-header">
  <nav>
    <ul>
      <li><%= link_to "The Cyclist in your Life", root_url %></li>
      <% if current_user %>
        <li><%= link_to "Get me outta ere!", logout_path, class: "logged_in" %></li>
        <li><%= link_to "My Profile", user_path(current_user)%></li>
        <li><%= link_to "Settings", edit_user_path(current_user)%></li>
      <% else %>
        <li><%= link_to "Registration", registration_path, class: "registration" %></li>
        <li><%= link_to "I want in!", login_path, class: "not_logged_in" %></li>
      <% end %>
      <li id="amazon-locale">Amazon Region: <%= select_tag(:aaws_locale_id, options_for_select([['US', 'us'], ['UK', 'uk']], 'uk')) %></li>
    </ul>
  </nav>
</header>

<%= render 'dialogs/user_registration' %>

<%= render 'dialogs/user_login' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Santa 4 Cyclists</title>
   
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <div class="inner-container">
      <%= yield %>
    </div>
  </div>

</body>
</html>